### PR TITLE
TG-79: Sidebar Employee-Admin

### PR DESCRIPTION
**Pull request by lucianofrailelopez**
SideBar:
Admin all entities are displayed.
Employee displays only Projects, Time-Sheet.
Part of the Router file was modified to show the different sidebars.

Warning: to be able to see the sidebar from an admin or from an employee you have to press the buttons (admin or employee).

### CODE REVIEW

**Review by Javier-Cervera — APPROVED** [review]
Looks good!

**Comment by LeonelListro** [comment]
# Test results

Tested locally on: https://alexis-trackgenix-app-git-feature-tg-79-emplo-d903f8-basp-m2022.vercel.app/home

## Test results: Failed ⚠️

bugs found:

1- Entity selector should change when you select one (should be bold or in another color)

Sin título

**Review by LeonelListro — CHANGES_REQUESTED** [review]
Test failed, please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/41#issuecomment-1166642456

**Review by LeonelListro — APPROVED** [review]
Well done Luciano and team!

**Pull request merged**
