### PR TITLE
BaSP-TG-121: Landing page and shared component "scroll to top"

### PR DESCRIPTION
**Pull request by NicolasFontana**
- A responsive landing page was created with their respective styles.
- Added a "scroll to top" shared component that can be seen on the landing page.
- In the home, login and sign up pages the sidebar was removed, and the routes were added in the header.

### CODE REVIEW

**Review by agusting19 — APPROVED** [review]
Looks awesome buddy!

**Comment by tinchorova** [comment]
## Test Results

Bugs found:
1. Learn more buttons don't have any function

Everything else looks pretty!

**Review by tinchorova — CHANGES_REQUESTED** [review]
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/71#issuecomment-1196673689

**Review by ArianaMaldonado — APPROVED** [review]
**Test Result: Passed ✅**

**Review by tinchorova — APPROVED** [review]

**Pull request merged**
