### PR TITLE
BaSP-TG-96: Fix routes

### PR DESCRIPTION
**Pull request by NicolasFontana**
Must be able to navigate correctly on the page. If we navigate to "/" it should take us to "/home" and if we want to access a non-existent route it takes us to a 404 error page - not found

Try this routes to see the changes: 
http://localhost:3000/asd. Expected result: open 404 page
http://localhost:3000/admin/adminsasd. Expected result: redirect to http://localhost:3000/admin
http://localhost:3000/admin/admins/asd. Expected result: redirect to http://localhost:3000/admin

### CODE REVIEW

**Review by Javier-Cervera — APPROVED** [review]
Looks amazing, good job!

Maybe delete the unused svg

**Review by agusting19 — APPROVED** [review]
Super clean buddy! Nice work

**Review by Johsua30 — APPROVED** [review]
Looks great. Nice additon

**Review by ArianaMaldonado — APPROVED** [review]
Test Result: Passed ✅

**Pull request merged**
