### PR TITLE
BaSP-TG-125: Redesign timesheet screen

### PR DESCRIPTION
**Pull request by iaracriscenti**
# Description

## Timesheet - Personal section
Added a section to **obtain a certain time-sheet**: by project and period. If that timesheet doesn't exist, a error message shows up.

When adding a timesheet, the project dropdown should only display projects that have been assigned to the employee and do not have already a timesheet in the current period.

By clicking a timesheet, the employee will be able to add/delete/edit tasks for that timesheet.

Show a warning if the employee hasn't uploaded timesheets yet.

If there is a timesheet created in a period different than the current one, the employee will not be able to add tasks.

## Timesheet - PM section
If the Employee is PM, a new section will be enabled: It will show all the timesheets of the employees that belong to the projects where the current Employee is PM. 

By clicking a timesheet, the PM will be able to see the tasks for that timesheet and approve/disapprove it.

### To consider:

Responsive styles were added

### CODE REVIEW

**Review by Javier-Cervera — APPROVED** [review]
Looks amazing, good job!

**Comment by ArianaMaldonado** [comment]
_Tested locally on: https://alexis-trackgenix-app-git-feature-tg-125-rede-9fc5f4-basp-m2022.vercel.app/_

**Test Result: Failed ⚠️** 

Bugs found:
1. When adding a task to my timesheet an error message keeps appearing.
Adding a task

2. When editing a taks of my timesheet the app crashed.
Editing a task

3. When trying to delete a task of my timesheet an error message keeps appearing.
Delete a task

4. When an Employee is not PM and has no Timesheet assigned the styles crashed:
image

5. As an Employee that is not PM and has no Projects assinged, if I try to add a new timesheet the message I get is the following:
NO projects
Timesheets

6. When trying to remove the approval of a task, an error message keeps appearing.
Remove approval

7. When accessing to the app from a mobile device, profile access is missing.
Profile form mobile version

**Review by ArianaMaldonado — CHANGES_REQUESTED** [review]
Changes requested. Please, refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/72#issuecomment-1198299913

**Review by ArianaMaldonado — APPROVED** [review]
**Test Result: Passed ✅**

**Pull request merged**
