### PR TITLE
BaSP-TG-42: Sidebar and Navbar creation/ Header and Footer final details

### PR DESCRIPTION
**Pull request by LuliBianchini**
### WORK DONE ON THE PR:
- It was created a Sidebar, according to the style provided in the Figma file.
- It was created a Navbar that leads the user or PO to all the table screens we've worked on the previous week, where they can visualize a list of each resource with their corresponding information.
- It was given style to the header and footer, apart from the sidebar.
- It was changed the syntax of the code in the navbar in order to implement React Router, which was one of the tasks of this week.

**OBSERVATIONS:**
- The model on Figma did not correspond to the style guide provided during the first stage of the project. The decision was to respect the format of the design but to use the colors given in the style guide 
- Username section has no functionality

### CODE REVIEW

**Review by agusting19 — APPROVED** [review]
Nice work!

**Review by Javier-Cervera — COMMENTED** [review]
The code and functionalities are well implemented.

**Comment by tinchorova** [comment]
## Testing Results
Tested locally on https://alexis-trackgenix-app-git-feature-tg-42-heade-77b80e-basp-m2022.vercel.app/

**Test Results: Failed**⚠️

Bugs found:
1. When user is on a section and clicks anywhere, the resource selection is unselected. Dot shows the click action.
image
image
2. When clicking on trackgenix logo it redirects to home but Home button in sidebar is not selected (In the images, going from admins section to home section)
image
image
3. (suggestion) Home button could be written Home instead of all caps (HOME)
4. There should be consistency with Super Admins wording (could take out the "-")
image

**Review by tinchorova — CHANGES_REQUESTED** [review]
Please refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/18#issuecomment-1151627072

**Comment by ArianaMaldonado** [comment]
Tested locally on: https://alexis-trackgenix-app-git-feature-tg-42-heade-77b80e-basp-m2022.vercel.app/home

**Test Result: Failed ⚠️** 

Bugs found:

1. Horizontal scroll shouldn't be necessary.
Screenshot from 2022-06-12 16-27-02

2. When scrolling horizontally, an empty space is found in header and footer.
Screenshot from 2022-06-12 16-35-14
Screenshot from 2022-06-12 16-35-23

4. Header and sidebar-header should coincide.
Screenshot from 2022-06-12 16-29-24

5. Header and footer height haven't been fixed.
Use pictures in point two as reference.

6. "Trackgenix" text in sidebar-header should be smaller.
Screenshot from 2022-06-12 16-39-19

**Review by ArianaMaldonado — CHANGES_REQUESTED** [review]
Changes requested. Please, refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/18#issuecomment-1153272602

**Comment by tinchorova** [comment]
## Test results
Tested locally on: https://alexis-trackgenix-app-git-feature-tg-42-heade-77b80e-basp-m2022.vercel.app/home

**Test Result: Failed** ⚠️

Bugs found:

1. When on a resource page, and the button selected (bold font), then clicking outside of the button (anywhere in the page) the font is not bold anymore. This bug is repeatable. Red dot represents a click.
image
image
2. When on a resource page, holding click and dragging another resource button will bold the second button and the previous one will stay selected too.
image
image

**Review by tinchorova — CHANGES_REQUESTED** [review]
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/18#issuecomment-1155717747

**Review by tinchorova — APPROVED** [review]

**Review by ArianaMaldonado — APPROVED** [review]
Test Result: Passed ✅

**Pull request merged**
