### PR TITLE
BaSP-TG-74: User Employee timesheet/table

### PR DESCRIPTION
**Pull request by Javier-Cervera**
### User Employee
The final product will be the User Employee Timesheet & Projects screens. Accessible from the Employee button or the Sidebar link.

Projects & Timesheet are just tables displaying data. The projects the employee is on, and the timesheets assigned to that employee from those projects.

The columns shown are similar to those in Figma.

### Table component
Each entity table inside the User Admin will be refactored to accept modifiers so we can:

- Format date, boolean, and other table data cells.
- Show timesheets/tasks/projects table data cells as a dropdown.
- Not show Edit & Delete buttons on User Employee Tables

### User Employee
- Until we implement authentication, Projects & Timesheet are the screens for a specific employee (a different employee can’t be selected).
- Start Date and Last Update of Timesheet & Projects will be added in a Backend PR
- Timesheet’s add hours functionality will be implemented later

### Table component
- Table data cell dropdown selection will be disabled on another PR

### CODE REVIEW

**Review by Johsua30 — APPROVED** [review]
Everything looks fine

**Review by LuliBianchini — APPROVED** [review]
Everything seems fine and routes work well!

**Review by NicolasFontana — APPROVED** [review]
Everything looks well

**Review by ArianaMaldonado — APPROVED** [review]
**Test Result: Passed ✅**

**Pull request merged**
