### PR TITLE
BaSP-TG-54: Edit projects shared components & redux

### PR DESCRIPTION
**Pull request by iaracriscenti**
### Task's brief description

- Make suggested changes to Edit Project screen.
- Add shared components (modals, inputs, buttons, and so on).
- Add delete team member feature.
- Implement Redux and make sure everything works fine --> edit a project and edit/add/delete a team member

**(This should be tested in Edit project section)**

### To consider: 
- Some validations are pending to fix (names and empty field error messages)
- Some shared components styles are pending to fix (black border and no cursor pointer on buttons, confirm delete modal aspect, modals doesn't darken the entire page).

### Bugs pending to fix:
- If the user wants to enter to add or remove a member from the project and nothing else, when he leaves the add/edit member form he sees the edit button and intuitively he will press it and he will not be able to advance because he gets an error message saying that "no changes were made" --> **This feature will be fixed in other ticket, already arranged with QA**
- When updating successfully a project the message should be: 'The project has been updated succesfully' --> **Will be fixed on the already opened PR in server repo**

### CODE REVIEW

**Review by agusting19 — APPROVED** [review]
Edit working clean!

**Review by Javier-Cervera — COMMENTED** [review]
Looks good! And the edit works

**Review by NicolasFontana — APPROVED** [review]
Nice work!

**Comment by tinchorova** [comment]
## Testing results

Tested locally on: https://alexis-trackgenix-app-git-feature-tg-54-add-e-db1411-basp-m2022.vercel.app/projects

**Test result: Failed** ⚠️

bugs found:

**Edit project**
1. When the user is on edit project form, editing the inputs and going to add members form does not save the changes nor warn the user that changes will be lost
2. Adding a new member to the project without changing other inputs is not possible because it pops a message saying no inputs changed. This applies for deleting a member too.
image
3. The message in point 2. could be 'No changes were made'
3. Clicking on submit button in add members form pops a message saying no inputs changed. Message could be 'No member selected'
image
4. Adding a new member message should be team members instead of member
image
5. Message should be 'The project has _been_ updated succesfully'
image

**Review by tinchorova — DISMISSED** [review]
Please refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/25#issuecomment-1159300706

**Comment by ArianaMaldonado** [comment]
Tested locally on: https://alexis-trackgenix-app-git-feature-tg-54-add-e-db1411-basp-m2022.vercel.app/

**Test Result: Failed ⚠️** 

> Bugs found:

1. The user is not able to edit a member, I understand that if I try to add the same member I see in the list I'm able to edit it but it's not intuitive, the user should be provided of an edit member option. Only delete and add functions are working.
Screenshot from 2022-06-20 12-50-19

**Review by ArianaMaldonado — APPROVED** [review]
**Test Result: Passed ✅** 
_Note: Pending changes to be reported in Trello ticket._

**Pull request merged**
