### PR TITLE
BaSP-TG-102: FE Admin Flow

### PR DESCRIPTION
**Pull request by iaracriscenti**
## Brief task description
Updated Admin flow. An Admin should be able to:

- see the list of employees and delete them
- see the list of projects and edit/delete them
- click on each table row and be redirected to another page

---
### Aditional modifications:
- Changed style and position of ADD button in Projects section
- Changed project modal form: team members table was removed
- Changed project and employee table headers: **PM column is only with 'Not selected' value and can't be edited for now**

---
### *To consider*:
- When adding/editing a project, the fields "Project" and "Client" are not allowed to contain spaces --> *there's already a ticket with this bug *
- When adding a project the field "end Date" is not required in the form (the validation will not be displayed) but it is still required in the Backend (the error modal will pop up) --> *there's already a ticket with this bug *
- The rows are clickable and soon will show the remaining info/functions such as add/delete/edit team members from a project or show employee's data --> *this features are developing in other ticket*

### CODE REVIEW

**Review by Javier-Cervera — APPROVED** [review]
Looks good!

**Review by Javier-Cervera — COMMENTED** [review]
Add/Edit Project form inputs:
Start Date and End Date could be shorter and on the same row

**Comment by iaracriscenti** [comment]
> Add/Edit Project form inputs: Start Date and End Date could be shorter and on the same row

Good detail! already on it

**Review by LeonelListro — APPROVED** [review]
Well done Iara and team!

**Pull request merged**
