### PR TITLE
BaSP-TG-73: Fix Buttons CSS

### PR DESCRIPTION
**Pull request by Johsua30**
Fix border in Shared Component Buttons and add the property of "cursor: pointer"

The change is visible in the tables(buttons no longer have borders)

### CODE REVIEW

**Review by NicolasFontana — APPROVED** [review]
Everything looks good! Well done

**Comment by ArianaMaldonado** [comment]
Tested locally on:

**Test Result: Failed ⚠️** 

Bugs found:
1. Every buttons on delete confirmation modal have borders.

Screenshot from 2022-06-25 15-34-17
Screenshot from 2022-06-25 15-33-38
Screenshot from 2022-06-25 15-33-16
Screenshot from 2022-06-25 15-32-48
Screenshot from 2022-06-25 15-34-57
Screenshot from 2022-06-25 15-34-38

**Review by ArianaMaldonado — CHANGES_REQUESTED** [review]
Changes requested. Please, refer to https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/44#issuecomment-1166341057

**Review by ArianaMaldonado — APPROVED** [review]
**Test Result: Passed ✅** 

_Note: Delete modal changes to be make - https://trello.com/c/UsoxYWoM_

**Pull request merged**
