### PR TITLE
BaSP-TG-103: Admin Project Row Screen

### PR DESCRIPTION
**Pull request by Javier-Cervera**
## Brief description

Click row --> Show project info and add/edit members Table

We can click on the member row to redirect to that employee's page on /admin/employees/:id

Also, when adding or removing a member, or deleting a Project, the change can be seen on the Admin/Employees screen, inside the Projects column of that Employee.

### Shared Components refactored

- Table: Conditionals added to be used with the members array of a Project

- Select: Conditional added so if the label is not declared, it doesn’t appear as a strip of a few pixels

- Input: Disabled option added so when editing a member, only role and rate can be changed

- Header: Refactor for IDs header (“Project: [id]”,** “Employee: [id]”**, etc)

### CODE REVIEW

**Review by agusting19 — APPROVED** [review]
Code look's good but i couldn't test it (firefox problems)

**Review by iaracriscenti — APPROVED** [review]
Everything works correctly and looks good, great job!!

**Comment by ArianaMaldonado** [comment]
_Tested locally on: https://alexis-trackgenix-app-git-feature-tg-103-admi-d23f9e-basp-m2022.vercel.app/_
**Test Result: Failed ⚠️** 

**Bugs found:**
1. The title of the Project info screen should be more descriptive. We have the id of the projects but what if we get: **"Project: _[id]_"**?
Screenshot from 2022-07-16 16-28-03

2. Same that item 1: the title of the section should be more descriptive. We have the id of the employee, but what if we get: **"Employee: [_id]_"**
Screenshot from 2022-07-16 16-32-02

3. We should have a button to come back to the previous screen.
**Project screen view:**
Screenshot from 2022-07-16 16-31-26

**Employee screen view:**
Screenshot from 2022-07-16 16-36-37

**Review by ArianaMaldonado — CHANGES_REQUESTED** [review]
Changes requested. Please, refer to: https://github.com/BaSP-m2022/alexis-trackgenix-app/pull/59#issuecomment-1186275274

**Review by ArianaMaldonado — APPROVED** [review]
**Test Result: Passed ✅ **

**Pull request merged**
